### ISSUE TITLE
GitHubで誤った操作をしてしまい自分のブランチのデータが消えた

### ISSUE THREAD

**Issue by AmuMotomura** [uedamasanari/school_develop_1#11]
GitHubで誤った操作をしてしまい自分のブランチのデータが消えた

**Comment by uedamasanari** [comment]
コミットしているデータが残っているので、そのコミットを右クリックした後にそのコミットから新しくブランチを作成すると前回コミットした時点でのブランチが出来上がる。
ここにデータが残っている可能性が高い

**Comment by uedamasanari** [comment]
データ戻った！
完了！
