### ISSUE TITLE
クローゼット画面エラー出た

### ISSUE THREAD

**Issue by nanakoooooo** [uedamasanari/school_develop_1#36]
Failed to compile
./src/pages/search.jsx
Error: 
  x the name `default` is exported multiple times
    ,-[/frontend/src/pages/search.jsx:2:1]
  2 |     import styles from '@/styles/Search.module.css'
  3 |     import {Link} from 'react-router-dom';
  4 |     
  5 | ,-> export default function Home() {
  6 | |     // const PlusButton = ({onClick}) ={
  7 | |   
  8 | |     // }
  9 | |     const LinkButton = () => {
 10 | |     }
 11 | |   
 12 | |     const MyComponent = () => {
 13 | |   
 14 | |     }
 15 | |   
 16 | |     return (
 17 | |           <div className="container">
 18 | |               <p className={styles.tagSearch}>タグ検索</p>
 19 | |               {/* <div className="plus-button" onClick={onClick}>＋</div> */}
 20 | |               <Link to={"./home.jsx"}>
 21 | |                 <button>+</button>
 22 | |               </Link>
 23 | |               <div>
 24 | |           </div>
 25 | |                   <p className={styles.tag}>#季節</p>
 26 | |                   <p className={styles.tag}>#柄</p>
 27 | |                   <p className={styles.tag}>#色</p>
 28 | |                   <p className={styles.tag}>#ブランド名  など</p>
 29 | |                   <div className="button-container"><button className={styles.button}>表示</button></div>
 30 | |           
 31 | |   
 32 | |           {/* <div className="container"> */}
 33 | |               <p className={styles.displayAll}>アイテムをすべて表示する</p>
 34 | |               <div className="button-container"><button className={styles.button}>表示</button></div>
 35 | |           {/* </div> */}
 36 | |   
 37 | |       </div>
 38 | |       
 39 | |     )
 40 | |-> }
    : `---- previous exported here
 41 |     
 42 | ,-> export default Home;
    : |^^^^^^^^^^|^^^^^^^^^
    : |          `-- exported more than once
 43 |     
 44 |     
    `----

Error: 
  > Exported identifiers must be unique
This error occurred during the build process and can only be dismissed by fixing the error.

**Comment by nanakoooooo** [comment]
./src/pages/search.jsx:3:0
Module not found: Can't resolve 'react-router-dom'
  1 | import React, { useState, useEffect } from 'react'
  2 | import styles from '@/styles/Search.module.css'
> 3 | import {Link} from 'react-router-dom';
  4 | 
  5 | export default function Home() {
  6 |   // const PlusButton = ({onClick}) ={

https://nextjs.org/docs/messages/module-not-found

**Comment by uedamasanari** [comment]
@nanakoooooo 
1つ目のエラーはexport defaultを2回以上書いているっていうエラーやね
コード確認してみて

2つ目のエラーはreact-router-domがインストールされてないっていうエラーだから、下のコマンドをターミナルで実行してみて
npm install react-router-dom

**Comment by nanakoooooo** [comment]
npm install react-router-dom
出てきた。。。あ

１個目のエラーは解決しました、ありがとう！

**Comment by nanakoooooo** [comment]
1個目解決した！ありがとうございます！！

2個目が
zsh: command not found: nodebrew
出てくる。。。

**Comment by nanakoooooo** [comment]
けどとりあえず今はエラー表示されてないから大丈夫かも！

**Comment by uedamasanari** [comment]
nodebrewエラーかー
mac使ってたっけ？
これ手順に沿ってインストールしてみて。ちょっとややこしいけど🙏
https://brew.sh/index_ja
